package web

import (
	"embed"
	"io/fs"
)

// embeddedDist is generated by the React/Vite build. Callers may pass
// EmbeddedAssets() through Options.Assets; leaving Assets nil selects the
// small built-in fallback page instead.
//
//go:embed all:dist
var embeddedDist embed.FS

func EmbeddedAssets() fs.FS {
	assets, err := fs.Sub(embeddedDist, "dist")
	if err != nil {
		return nil
	}
	return assets
}
